"""Tool schemas package. Assembles the full schema list from per-category modules."""

from .navigation  import NAVIGATE, GO_BACK, GO_FORWARD, RELOAD, SCHEMAS as NAVIGATION_SCHEMAS
from .interaction import CLICK, FILL, PRESS_KEY, HOVER, SELECT_OPTION, DRAG_AND_DROP, SCHEMAS as INTERACTION_SCHEMAS
from .extraction  import GET_PAGE_CONTENT, FIND_ELEMENTS, GET_INTERACTIVE_ELEMENTS, EXECUTE_JS, SCHEMAS as EXTRACTION_SCHEMAS
from .scroll      import SCROLL, SCROLL_TO_ELEMENT, SCROLL_TO_BOTTOM, SCROLL_TO_TOP, SCHEMAS as SCROLL_SCHEMAS
from .wait        import WAIT_FOR_ELEMENT, WAIT_FOR_LOAD, WAIT_FOR_URL, SCHEMAS as WAIT_SCHEMAS
from .control     import DONE, SCHEMAS as CONTROL_SCHEMAS

TOOL_SCHEMAS = (
    NAVIGATION_SCHEMAS
    + INTERACTION_SCHEMAS
    + EXTRACTION_SCHEMAS
    + SCROLL_SCHEMAS
    + WAIT_SCHEMAS
    + CONTROL_SCHEMAS
)

__all__ = [
    "TOOL_SCHEMAS",
    "NAVIGATION_SCHEMAS", "INTERACTION_SCHEMAS", "EXTRACTION_SCHEMAS",
    "SCROLL_SCHEMAS", "WAIT_SCHEMAS", "CONTROL_SCHEMAS",
    "NAVIGATE", "GO_BACK", "GO_FORWARD", "RELOAD",
    "CLICK", "FILL", "PRESS_KEY", "HOVER", "SELECT_OPTION", "DRAG_AND_DROP",
    "GET_PAGE_CONTENT", "FIND_ELEMENTS", "GET_INTERACTIVE_ELEMENTS", "EXECUTE_JS",
    "SCROLL", "SCROLL_TO_ELEMENT", "SCROLL_TO_BOTTOM", "SCROLL_TO_TOP",
    "WAIT_FOR_ELEMENT", "WAIT_FOR_LOAD", "WAIT_FOR_URL",
    "DONE",
]
